### ISSUE TITLE
Getting "Permission denied" error on main at 7a32134

### ISSUE THREAD

**Issue by mattd** [manuscriptmastr/kafi-shop#1]
`sh: ./dist/index.js: Permission denied`

index.js is getting generated without the executable bit, but I'm not certain that's the problem. Everything was working fine with the previous version I'd checked out - but I'm not sure where that was. :)

**Comment by manuscriptmastr** [comment]
Hi @mattd! This might be due to me recently opting for a NPM script command instead of adding `kafi-shop` to the bin via `npm link`. Per the updated README, **you'll want to explicitly run `chmod +x ./dist/index.js` after cloning the repo.** This enables `npm run shop ...` to "just work" afterward.

I'd love to find a way around that extra step, though, if you have any suggestions! My main blocker right now is my brain.

**Comment by manuscriptmastr** [comment]
Update: I've gone back to the `npm link` strategy, so I don't think you need to enable that permission anymore.
